### ISSUE TITLE
Why does `Resource.respond()` call `next()` at the end

### ISSUE THREAD

**Issue by makinde** [travist/resourcejs#89]
It seems like that method handles sending a response. By calling next, other middleware on the app continue to get run, which means a central 404 handler will eventually get called if the express app is doing other things.

Would it make sense to remove line 159 in Resource.js?

**Comment by travist** [comment]
It calls next() because a lot can and should happen AFTER the server sends a response to the client. Many Express.js developers believe that the server just stops after the response has been made, but much can and should happen afterwards. For example, you should always put "analytics" calls after a response has been made. The reason for this is that there is no need to call the analytics middleware before the response, and it will just add cycles to the server before the user receives their response. This can make applications seem "sluggish" since they are executing a lot of cycles before they provide their response. Hope this helps.

**Comment by makinde** [comment]
Ah, thanks for the context.
